# Generated by Django 2.2.20 on 2021-09-17 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_appeal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flat_appeals', to='property.Flat', verbose_name='На какую квартиру жалоба'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='text',
            field=models.TextField(verbose_name='Текст жалобы'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_appeals', to=settings.AUTH_USER_MODEL, verbose_name='Кто пожаловался'),
        ),
    ]
