# Generated by Django 2.2.20 on 2021-09-17 09:54

from django.db import migrations

import phonenumbers


def fill_normalized_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        parsed_phone = phonenumbers.parse(flat.owners_phonenumber, "RU")
        flat.owner_pure_phone = phonenumbers.format_number(
            parsed_phone, phonenumbers.PhoneNumberFormat.E164)
        flat.save()


def reset_normalized_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owner_pure_phone = None
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(
            fill_normalized_phone_numbers,
            reset_normalized_phone_numbers
        )
    ]
